export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const FETCH_AUTH = "FETCH_AUTH";
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS";
export const FETCH_AUTH_FAILURE = "FETCH_AUTH_FAILURE";
export const OUT_AUTH = "OUT_AUTH"

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const MODAL_TYPE_REGISTRATION = "MODAL_TYPE_REGISTRATION"
export const MODAL_TYPE_LOGIN = "MODAL_TYPE_LOGIN"

export const FETCH_USER_PAGE = "FETCH_USER_PAGE";
export const FETCH_USER_PAGE_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_PAGE_FAILURE = "FETCH_USER_FAILURE";
